### ISSUE TITLE
False gesture triggers

### ISSUE THREAD

**Issue by stanfordbinet** [vantoman/kernel_xiaomi_davinci#3]
Hi! 

I hope this is the right way to report an issue, I (and others) are experiencing while using Vantom Kernel on our davinci devices. I'm also not 100% sure, if this is strictly/purely related to a kernel bug itself (or at all).

**Swiping up from the home-screen (using Android10 gesture navigation) - occasionally - falsely triggers recent apps - instead of the app drawer.** 

With different kernels on these ROMs, a (quick) continuous swipe up motion (short or long), opens the  App drawer 100/100 times. Using the "stock" Vantom kernel (included in Havoc, EvoX) or flashing Vantom on PE (tried v148 and v150) results in the above described issue.

Thanks in advance for any feedback!

**Comment by vantoman** [comment]
i couldn't reproduce and i dont think its kernel related
