### ISSUE TITLE
Dc dimming working bad for my eyes (maybe not only for me)

### ISSUE THREAD

**Issue by 6y6Jl9** [vantoman/kernel_xiaomi_davinci#6]
Hello, Vantoman! Can u make a test kernel with dc dimming from pancake kernel for Android 11?: (https://github.com/mishamyrt/davinci-pancake-kernel). Because ur realization dc dimming does not help with eye pain and headache for me, and maybe for more users. Im using pancake kernel on a10 a long time and it works fine for me! The developer has stopped working on the kernel a11 version is not available, so I ask you about it. Sorry for my bad english. Thx!

**Comment by vantoman** [comment]
its fine for me and for many other users 
you can keep using the kernel you mentioned or you better get a another device
